name: Deploy Backend Production Gartanggali

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_PATH: /home/apps/gartanggalibackend
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Copy files to deployment folder
      - name: Copy files to deploy folder
        run: |
          mkdir -p $DEPLOY_PATH/dist
          mkdir -p $DEPLOY_PATH/prisma
          rsync -av ./dist/ $DEPLOY_PATH/dist/
          rsync -av ./prisma/ $DEPLOY_PATH/prisma/
          rsync -av package.json package-lock.json $DEPLOY_PATH/

      # 6️⃣ Install production dependencies
      - name: Install production dependencies
        run: |
          cd $DEPLOY_PATH
          npm ci --only=production

      # 7️⃣ Run Prisma migrations
      - name: Run Prisma migrations
        run: |
          cd $DEPLOY_PATH
          export $(grep -v '^#' .env | xargs)
          npx prisma migrate deploy

      # 8️⃣ Generate Prisma client
      - name: Generate Prisma client
        run: |
          cd $DEPLOY_PATH
          export $(grep -v '^#' .env | xargs)
          npx prisma generate


      # 9️⃣ Restart server (using PM2)
      - name: Restart server
        run: |
          cd $DEPLOY_PATH
          npx pm2 reload gartanggali || npx pm2 start npm --name gartanggali -- start
